name: al_quran
description: Flutter App for the holy book of Qur'an.

version: 1.0.2+5

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^1.0.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  http: ^0.13.4
  shimmer: ^2.0.0
  shared_preferences: ^2.0.8
  provider: ^6.0.1
  share: ^2.0.4
  url_launcher: ^6.0.12
  flutter_overboard: ^3.0.0
  flutter_svg: ^0.23.0+1

  hive: ^2.0.4
  hive_flutter: ^1.1.0

  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # cache local storage
  build_runner: ^2.1.5
  hive_generator: ^1.1.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: Sogeo
      fonts:
        - asset: fonts/sui.ttf
    #     - asset: fonts/Raleway-Italic.ttf
    #       style: italic
    - family: ShareIcon
      fonts:
        - asset: fonts/ShareIcon.ttf
